name: linux-basic
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - run: gh repo clone $GITHUB_REPOSITORY -- --depth 1
#     - uses: mxschmitt/action-tmate@master
