name: windows
on:
  workflow_dispatch:

jobs:
  build:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: windows-latest
    steps:
      - run: |
          ls
          pwd
          bash -c ls
          bash -c pwd
